name: Release preaparation
on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io

jobs:

  build-and-pack:
    name: Build and pack
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ACCESS_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Build container
        run: docker build -t ghcr.io/${{ github.repository_owner }}/stack:0.1.0 .
    
      - name: Push image
        run:  docker push ghcr.io/${{ github.repository_owner }}/stack:0.1.0
